---
- name: Pull Docker Image of Calculator
  hosts: all
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3.8
  tasks:
    - name: Pull image
      docker_image:
        name: madhavsood04/calculator:latest
        source: pull
    - name: Start docker service
      service:
        name: docker
        state: started
    - name: Stop the container with same name if it already exists before deleting
      shell: docker stop Calculator
      ignore_errors: true
    - name: Delete container with same name if it already exists
      shell: docker rm Calculator
      ignore_errors: true
    - name: Running container
      shell: docker run -it -d --name Calculator madhavsood04/calculator

